# Generated by Django 5.2 on 2025-04-28 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название качества')),
                ('description', models.TextField(blank=True, verbose_name='Описание качества')),
                ('drop_chance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Шанс выпадения')),
            ],
            options={
                'verbose_name': 'Качество предмета',
                'verbose_name_plural': 'Качества предметов',
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_prototype', models.BooleanField(default=False, verbose_name='Является образцом')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gears', to='gear.itemquality', verbose_name='Качество снаряжения')),
            ],
            options={
                'verbose_name': 'Cнаряжение',
                'verbose_name_plural': 'Снаряжения',
            },
        ),
    ]
